# Generated by Django 3.2 on 2021-04-11 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Game')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='startGame')),
                ('date_end', models.DateTimeField(help_text='время окончания игры', null=True, verbose_name='endGame')),
                ('status', models.SmallIntegerField(choices=[(1, 'Started'), (0, 'Finished')], default=1)),
                ('winner', models.CharField(max_length=50, null=True, verbose_name='Победитель')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ship', models.CharField(max_length=250, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'ready'), (2, 'not_ready')], default=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_of_ships.game', verbose_name='UUID')),
            ],
        ),
    ]
