# Generated by Django 3.2 on 2021-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_of_ships', '0002_alter_user_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ship',
            field=models.JSONField(null=True),
        ),
    ]
